### ISSUE TITLE
after running test.py port 10808 is not in use.

### ISSUE THREAD

**Issue by Ulysses0817** [tom-snow/docker-ComWechat#1]
## 问题:
你好，大佬～有两个问题想要请教一下：
1. test.py文件中18888端口和10808端口的定位和作用，运行文件后，18888端口占用情况有变化，而10808端口仍是未占用状态。
2. test.py运行过程中，新开一个python文件，执行post_wechat_http_api(15或1, port=18888)会处于长时间无响应状态，port参数设置为10808则直接报refused错误。

我感觉可能是我对下面代码的理解可能有偏差，但是找不到对应的解决方式。。烦请大佬有空了帮忙指导下～
`print(post_wechat_http_api(APIS.WECHAT_MSG_START_HOOK, port, {"port": `10808}))`与`start_socket_server()`
我对start_socket_server的理解是，默认参数port为10808，运行后会只要不关闭程序会一直监听该机器上10808端口。之后新创建py文件，在里面编写调用`post_wechat_http_api(操作类型, 10808, dict类型的参数变量)`即可。

## 背景
已按下列步骤走完流程：
1. 运行上方命令启动镜像(更推荐使用 [docker-compose](https://github.com/tom-snow/docker-ComWechat/blob/main/docker-compose.yaml) )
3. 连接上 VNC 扫码登陆微信(建议扫码登陆后把微信的版本号弹窗等关闭)
4. 直接在机器上启动示例文件 [test.py](https://github.com/tom-snow/docker-ComWechat/blob/main/test.py) 

python3 test.py的最后输出如下：
<img width="892" alt="image" src="https://user-images.githubusercontent.com/29434950/206849012-2e869527-5db1-4c4c-9e39-ee64b72b8e60.png">

然后查看端口占用如下：
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/29434950/206849028-007533e5-6d7d-4869-bfef-3db53049d77f.png">

**Comment by tom-snow** [comment]
如果你是打算使用 EFB 用 telegram 进行微信消息收发的话，建议直接使用  [https://github.com/0honus0/efb-wechat-comwechat-slave/blob/master/docker-compose.yaml](https://github.com/0honus0/efb-wechat-comwechat-slave/blob/master/docker-compose.yaml) 快速配置。

如果是想了解工作原理的话看图：

![image](https://user-images.githubusercontent.com/79245287/206851190-978ab267-4f37-4fa6-ad61-f1c50f860e62.png)

**Comment by Ulysses0817** [comment]
> 如果你是打算使用 EFB 用 telegram 进行微信消息收发的话，建议直接使用 https://github.com/0honus0/efb-wechat-comwechat-slave/blob/master/docker-compose.yaml 快速配置。
> 
> 如果是想了解工作原理的话看图：
> 
> ![image](https://user-images.githubusercontent.com/79245287/206851190-978ab267-4f37-4fa6-ad61-f1c50f860e62.png)

感谢回复！
1. 我想不通过tg转发，直接构建机器人～
   有看过[efb-wechat-comwechat-slave](https://github.com/0honus0/efb-wechat-comwechat-slave)和[efb-telegram-master](https://github.com/ehForwarderBot/efb-telegram-master),但是在efb-telegram-master里没找到对efb-wechat-comwechat-slave封装的机器人的调用示例额。
   
2. 有看到这个注释，但是没发现`post_wechat_http_api(APIS.WECHAT_MSG_START_HOOK, port, {"port": 10808})`有发挥任何作用，所以不太理解。。。
比如运行test.py后，看日志{'msg':1, 'result':'OK'}好像是成功开启接受消息hook，但是微信上收发消息，test.py的日志没有任何变化，一致停留在
<img width="242" alt="image" src="https://user-images.githubusercontent.com/29434950/206854336-e0647f1a-df34-45e9-a922-c6f8ef43c09f.png">
而且10808端口也没有任何进程占用，向post_wechat_http_api 向10808端口发请求也connection refused。


再就是看到了[ComWeChatRobot](https://github.com/ljc545w/ComWeChatRobot)给出的[Wxdriver.py](https://github.com/ljc545w/ComWeChatRobot/blob/c43b82078d07230524568fad44825e3868afef19/Python/http/wxDriver.py)，发现少了调用dll中的接口，对wechat.exe进行监听，我想的大佬你的docker中已经默认通过18888来监听wechat.exe了，不知道理解的对不对？
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/29434950/206854508-f95fde1b-a0ed-4aac-b393-f8538eeb8975.png">

3. 我想我的根本问题是，由于对于网络通信不熟悉，所以我不太理解`start_socket_server()`——启动socket服务之后，为什么执行post_wechat_http_api(15或1, port=18888)会处于长时间无响应状态，port参数设置为10808则直接报refused错误。难道说是10808端口其实没有在监听客户端发送过去的消息？

**Comment by Ulysses0817** [comment]
已解决

**Comment by EkkoLin** [comment]
怎么解决的？我跑python3 test.py依然是找不到18888和10808 port.
