### ISSUE TITLE
test.py: Bug in setting the version number?

### ISSUE THREAD

**Issue by xixixi2000** [tom-snow/docker-ComWechat#6]
resp = requests.get(url = "https://api.github.com/repos/tom-snow/wechat-windows-versions/releases?per_page=1",params = {"per_page": 1})
    latest_version = resp.json()[0]["tag_name"].replace("v","")

   There is a "v" in the front of the version number, so the set version number function may get a wrong number set to the wechat

**Comment by tom-snow** [comment]
Thanks.
